/*
 * OFxPERA API
 * Philippines Open Finance API Implementation for PERA
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ConsentHistoryEvents;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ConsentHistory
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-24T23:12:52.341191218Z[GMT]")

public class ConsentHistory {
  @SerializedName("id")
  private String id = null;

  @SerializedName("events")
  private List<ConsentHistoryEvents> events = new ArrayList<ConsentHistoryEvents>();

  public ConsentHistory id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the consent arrangement
   * @return id
  **/
  @Schema(required = true, description = "The ID of the consent arrangement")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ConsentHistory events(List<ConsentHistoryEvents> events) {
    this.events = events;
    return this;
  }

  public ConsentHistory addEventsItem(ConsentHistoryEvents eventsItem) {
    this.events.add(eventsItem);
    return this;
  }

   /**
   * Get events
   * @return events
  **/
  @Schema(required = true, description = "")
  public List<ConsentHistoryEvents> getEvents() {
    return events;
  }

  public void setEvents(List<ConsentHistoryEvents> events) {
    this.events = events;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentHistory consentHistory = (ConsentHistory) o;
    return Objects.equals(this.id, consentHistory.id) &&
        Objects.equals(this.events, consentHistory.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, events);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentHistory {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
