/*
 * OFxPERA API
 * Philippines Open Finance API Implementation for PERA
 *
 * OpenAPI spec version: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ConsentArrangementRequestAdditionalTerms;
import io.swagger.client.model.ConsentArrangementRequestSharingDuration;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ConsentArrangementRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-03T23:36:15.658195047Z[GMT]")

public class ConsentArrangementRequest {
  @SerializedName("data_holder_id")
  private String dataHolderId = null;

  /**
   * Gets or Sets permissions
   */
  @JsonAdapter(PermissionsEnum.Adapter.class)
  public enum PermissionsEnum {
    @SerializedName("PERA_BASIC_INFO")
    BASIC_INFO("PERA_BASIC_INFO"),
    @SerializedName("PERA_BALANCE")
    BALANCE("PERA_BALANCE"),
    @SerializedName("PERA_TRANSACTIONS")
    TRANSACTIONS("PERA_TRANSACTIONS"),
    @SerializedName("PERA_INVESTMENT_DETAILS")
    INVESTMENT_DETAILS("PERA_INVESTMENT_DETAILS"),
    @SerializedName("PERA_STATEMENTS")
    STATEMENTS("PERA_STATEMENTS");

    private String value;

    PermissionsEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static PermissionsEnum fromValue(String input) {
      for (PermissionsEnum b : PermissionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<PermissionsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PermissionsEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public PermissionsEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return PermissionsEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("permissions")
  private List<PermissionsEnum> permissions = new ArrayList<PermissionsEnum>();

  @SerializedName("sharing_duration")
  private ConsentArrangementRequestSharingDuration sharingDuration = null;

  @SerializedName("purpose")
  private String purpose = null;

  @SerializedName("additional_terms")
  private List<ConsentArrangementRequestAdditionalTerms> additionalTerms = null;

  public ConsentArrangementRequest dataHolderId(String dataHolderId) {
    this.dataHolderId = dataHolderId;
    return this;
  }

   /**
   * Identifier of the data holder (financial institution)
   * @return dataHolderId
  **/
  @Schema(required = true, description = "Identifier of the data holder (financial institution)")
  public String getDataHolderId() {
    return dataHolderId;
  }

  public void setDataHolderId(String dataHolderId) {
    this.dataHolderId = dataHolderId;
  }

  public ConsentArrangementRequest permissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
    return this;
  }

  public ConsentArrangementRequest addPermissionsItem(PermissionsEnum permissionsItem) {
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Permissions being requested for data access
   * @return permissions
  **/
  @Schema(required = true, description = "Permissions being requested for data access")
  public List<PermissionsEnum> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
  }

  public ConsentArrangementRequest sharingDuration(ConsentArrangementRequestSharingDuration sharingDuration) {
    this.sharingDuration = sharingDuration;
    return this;
  }

   /**
   * Get sharingDuration
   * @return sharingDuration
  **/
  @Schema(required = true, description = "")
  public ConsentArrangementRequestSharingDuration getSharingDuration() {
    return sharingDuration;
  }

  public void setSharingDuration(ConsentArrangementRequestSharingDuration sharingDuration) {
    this.sharingDuration = sharingDuration;
  }

  public ConsentArrangementRequest purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Purpose for which the data will be used
   * @return purpose
  **/
  @Schema(required = true, description = "Purpose for which the data will be used")
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public ConsentArrangementRequest additionalTerms(List<ConsentArrangementRequestAdditionalTerms> additionalTerms) {
    this.additionalTerms = additionalTerms;
    return this;
  }

  public ConsentArrangementRequest addAdditionalTermsItem(ConsentArrangementRequestAdditionalTerms additionalTermsItem) {
    if (this.additionalTerms == null) {
      this.additionalTerms = new ArrayList<ConsentArrangementRequestAdditionalTerms>();
    }
    this.additionalTerms.add(additionalTermsItem);
    return this;
  }

   /**
   * Additional terms and conditions specific to this arrangement
   * @return additionalTerms
  **/
  @Schema(description = "Additional terms and conditions specific to this arrangement")
  public List<ConsentArrangementRequestAdditionalTerms> getAdditionalTerms() {
    return additionalTerms;
  }

  public void setAdditionalTerms(List<ConsentArrangementRequestAdditionalTerms> additionalTerms) {
    this.additionalTerms = additionalTerms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentArrangementRequest consentArrangementRequest = (ConsentArrangementRequest) o;
    return Objects.equals(this.dataHolderId, consentArrangementRequest.dataHolderId) &&
        Objects.equals(this.permissions, consentArrangementRequest.permissions) &&
        Objects.equals(this.sharingDuration, consentArrangementRequest.sharingDuration) &&
        Objects.equals(this.purpose, consentArrangementRequest.purpose) &&
        Objects.equals(this.additionalTerms, consentArrangementRequest.additionalTerms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataHolderId, permissions, sharingDuration, purpose, additionalTerms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentArrangementRequest {\n");
    
    sb.append("    dataHolderId: ").append(toIndentedString(dataHolderId)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    sharingDuration: ").append(toIndentedString(sharingDuration)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    additionalTerms: ").append(toIndentedString(additionalTerms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
