/*
 * OFxPERA API
 * Philippines Open Finance API Implementation for PERA
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * IdType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-24T23:12:52.341191218Z[GMT]")

public class IdType {
  @SerializedName("idNumber")
  private String idNumber = null;

  @SerializedName("idExpiryDate")
  private LocalDate idExpiryDate = null;

  @SerializedName("idType")
  private String idType = null;

  public IdType idNumber(String idNumber) {
    this.idNumber = idNumber;
    return this;
  }

   /**
   * Get idNumber
   * @return idNumber
  **/
  @Schema(required = true, description = "")
  public String getIdNumber() {
    return idNumber;
  }

  public void setIdNumber(String idNumber) {
    this.idNumber = idNumber;
  }

  public IdType idExpiryDate(LocalDate idExpiryDate) {
    this.idExpiryDate = idExpiryDate;
    return this;
  }

   /**
   * Format is YYYY-MM-DD
   * @return idExpiryDate
  **/
  @Schema(description = "Format is YYYY-MM-DD")
  public LocalDate getIdExpiryDate() {
    return idExpiryDate;
  }

  public void setIdExpiryDate(LocalDate idExpiryDate) {
    this.idExpiryDate = idExpiryDate;
  }

  public IdType idType(String idType) {
    this.idType = idType;
    return this;
  }

   /**
   * ID Type (e.g., \&quot;Drivers License\&quot;, \&quot;Passport\&quot;, etc.)
   * @return idType
  **/
  @Schema(required = true, description = "ID Type (e.g., \"Drivers License\", \"Passport\", etc.)")
  public String getIdType() {
    return idType;
  }

  public void setIdType(String idType) {
    this.idType = idType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdType idType = (IdType) o;
    return Objects.equals(this.idNumber, idType.idNumber) &&
        Objects.equals(this.idExpiryDate, idType.idExpiryDate) &&
        Objects.equals(this.idType, idType.idType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idNumber, idExpiryDate, idType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdType {\n");
    
    sb.append("    idNumber: ").append(toIndentedString(idNumber)).append("\n");
    sb.append("    idExpiryDate: ").append(toIndentedString(idExpiryDate)).append("\n");
    sb.append("    idType: ").append(toIndentedString(idType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
