/*
 * OFxPERA API
 * Philippines Open Finance API Implementation for PERA
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2001
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-24T23:12:52.341191218Z[GMT]")

public class InlineResponse2001 {
  @SerializedName("sub")
  private String sub = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("given_name")
  private String givenName = null;

  @SerializedName("family_name")
  private String familyName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("email_verified")
  private Boolean emailVerified = null;

  @SerializedName("phone_number")
  private String phoneNumber = null;

  @SerializedName("phone_number_verified")
  private Boolean phoneNumberVerified = null;

  public InlineResponse2001 sub(String sub) {
    this.sub = sub;
    return this;
  }

   /**
   * Unique identifier for the user from the authentication provider&#x27;s perspective.
   * @return sub
  **/
  @Schema(description = "Unique identifier for the user from the authentication provider's perspective.")
  public String getSub() {
    return sub;
  }

  public void setSub(String sub) {
    this.sub = sub;
  }

  public InlineResponse2001 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full name of the user.
   * @return name
  **/
  @Schema(description = "Full name of the user.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2001 givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Given name of the user.
   * @return givenName
  **/
  @Schema(description = "Given name of the user.")
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public InlineResponse2001 familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * Family name of the user.
   * @return familyName
  **/
  @Schema(description = "Family name of the user.")
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public InlineResponse2001 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email address of the user.
   * @return email
  **/
  @Schema(description = "Email address of the user.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InlineResponse2001 emailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
    return this;
  }

   /**
   * Indicates whether the user&#x27;s email address has been verified.
   * @return emailVerified
  **/
  @Schema(description = "Indicates whether the user's email address has been verified.")
  public Boolean isEmailVerified() {
    return emailVerified;
  }

  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }

  public InlineResponse2001 phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number of the user.
   * @return phoneNumber
  **/
  @Schema(description = "Phone number of the user.")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public InlineResponse2001 phoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
    return this;
  }

   /**
   * Indicates whether the user&#x27;s phone number has been verified.
   * @return phoneNumberVerified
  **/
  @Schema(description = "Indicates whether the user's phone number has been verified.")
  public Boolean isPhoneNumberVerified() {
    return phoneNumberVerified;
  }

  public void setPhoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.sub, inlineResponse2001.sub) &&
        Objects.equals(this.name, inlineResponse2001.name) &&
        Objects.equals(this.givenName, inlineResponse2001.givenName) &&
        Objects.equals(this.familyName, inlineResponse2001.familyName) &&
        Objects.equals(this.email, inlineResponse2001.email) &&
        Objects.equals(this.emailVerified, inlineResponse2001.emailVerified) &&
        Objects.equals(this.phoneNumber, inlineResponse2001.phoneNumber) &&
        Objects.equals(this.phoneNumberVerified, inlineResponse2001.phoneNumberVerified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sub, name, givenName, familyName, email, emailVerified, phoneNumber, phoneNumberVerified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberVerified: ").append(toIndentedString(phoneNumberVerified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
