/*
 * OFxPERA API
 * Philippines Open Finance API Implementation for PERA
 *
 * OpenAPI spec version: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.JWKSetKeys;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * JWKSet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-24T23:12:52.341191218Z[GMT]")

public class JWKSet implements JwksConfiguration {
  @SerializedName("keys")
  private List<JWKSetKeys> keys = new ArrayList<JWKSetKeys>();

  public JWKSet keys(List<JWKSetKeys> keys) {
    this.keys = keys;
    return this;
  }

  public JWKSet addKeysItem(JWKSetKeys keysItem) {
    this.keys.add(keysItem);
    return this;
  }

   /**
   * Array of JWK values representing public keys for verifying JWTs
   * @return keys
  **/
  @Schema(required = true, description = "Array of JWK values representing public keys for verifying JWTs")
  public List<JWKSetKeys> getKeys() {
    return keys;
  }

  public void setKeys(List<JWKSetKeys> keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JWKSet jwKSet = (JWKSet) o;
    return Objects.equals(this.keys, jwKSet.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JWKSet {\n");
    
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
