package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.model.PeraAccountBalance;
import io.swagger.model.PeraProduct;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
import org.springframework.validation.annotation.Validated;
import org.openapitools.jackson.nullable.JsonNullable;
import io.swagger.configuration.NotUndefined;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * PeraAccount
 */
@Validated
@NotUndefined
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-03-24T23:14:39.487511291Z[GMT]")


public class PeraAccount   {
  @JsonProperty("id")

  private String id = null;

  @JsonProperty("account_id")

  private String accountId = null;

  @JsonProperty("creation_date")

  private OffsetDateTime creationDate = null;

  @JsonProperty("product")

  @JsonInclude(JsonInclude.Include.NON_ABSENT)  // Exclude from JSON if absent
  @JsonSetter(nulls = Nulls.FAIL)    // FAIL setting if the value is null
  private PeraProduct product = null;

  @JsonProperty("balance")

  @JsonInclude(JsonInclude.Include.NON_ABSENT)  // Exclude from JSON if absent
  @JsonSetter(nulls = Nulls.FAIL)    // FAIL setting if the value is null
  private PeraAccountBalance balance = null;


  public PeraAccount id(String id) { 

    this.id = id;
    return this;
  }

  /**
   * Generated by the PERA admin, this is the unique identifier of the customer's PERA account
   * @return id
   **/
  
  @Schema(required = true, description = "Generated by the PERA admin, this is the unique identifier of the customer's PERA account")
  
  @NotNull
  public String getId() {  
    return id;
  }



  public void setId(String id) { 

    this.id = id;
  }

  public PeraAccount accountId(String accountId) { 

    this.accountId = accountId;
    return this;
  }

  /**
   * PERA Administrator's unique identifier for the customer's PERA account
   * @return accountId
   **/
  
  @Schema(required = true, description = "PERA Administrator's unique identifier for the customer's PERA account")
  
  @NotNull
  public String getAccountId() {  
    return accountId;
  }



  public void setAccountId(String accountId) { 

    this.accountId = accountId;
  }

  public PeraAccount creationDate(OffsetDateTime creationDate) { 

    this.creationDate = creationDate;
    return this;
  }

  /**
   * Date and time when the PERA account was created
   * @return creationDate
   **/
  
  @Schema(required = true, description = "Date and time when the PERA account was created")
  
@Valid
  @NotNull
  public OffsetDateTime getCreationDate() {  
    return creationDate;
  }



  public void setCreationDate(OffsetDateTime creationDate) { 

    this.creationDate = creationDate;
  }

  public PeraAccount product(PeraProduct product) { 

    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
   **/
  
  @Schema(description = "")
  
@Valid
  public PeraProduct getProduct() {  
    return product;
  }



  public void setProduct(PeraProduct product) { 
    this.product = product;
  }

  public PeraAccount balance(PeraAccountBalance balance) { 

    this.balance = balance;
    return this;
  }

  /**
   * Get balance
   * @return balance
   **/
  
  @Schema(description = "")
  
@Valid
  public PeraAccountBalance getBalance() {  
    return balance;
  }



  public void setBalance(PeraAccountBalance balance) { 
    this.balance = balance;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeraAccount peraAccount = (PeraAccount) o;
    return Objects.equals(this.id, peraAccount.id) &&
        Objects.equals(this.accountId, peraAccount.accountId) &&
        Objects.equals(this.creationDate, peraAccount.creationDate) &&
        Objects.equals(this.product, peraAccount.product) &&
        Objects.equals(this.balance, peraAccount.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountId, creationDate, product, balance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeraAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
