/*
 * OFxPERA API
 * Philippines Open Finance API Implementation for PERA
 *
 * OpenAPI spec version: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CustomerInformation;
import io.swagger.client.model.EndorsementResponse;
import io.swagger.client.model.Error;
import org.threeten.bp.OffsetDateTime;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CommonApi
 */
@Ignore
public class CommonApiTest {

    private final CommonApi api = new CommonApi();

    /**
     * [DEPRECATED] Forward customer endorsement
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void forwardCustomerEndorsementTest() throws Exception {
        String endorsement = null;
        String participantId = null;
        Integer xV = null;
        OffsetDateTime xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xClientHeaders = null;
        String xClientUserAgent = null;
        UUID xIdempotencyKey = null;
        OffsetDateTime xFapiCustomerLastLoggedTime = null;
        UUID xFapiInteractionId = null;
        EndorsementResponse response = api.forwardCustomerEndorsement(endorsement, participantId, xV, xFapiAuthDate, xFapiCustomerIpAddress, xClientHeaders, xClientUserAgent, xIdempotencyKey, xFapiCustomerLastLoggedTime, xFapiInteractionId);

        // TODO: test validations
    }
    /**
     * [PHASE 1] Get detailed customer information
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomerDetailTest() throws Exception {
        String customerId = null;
        String authorization = null;
        String participantId = null;
        Integer xV = null;
        OffsetDateTime xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xClientHeaders = null;
        String xClientUserAgent = null;
        UUID xIdempotencyKey = null;
        OffsetDateTime xFapiCustomerLastLoggedTime = null;
        UUID xFapiInteractionId = null;
        CustomerInformation response = api.getCustomerDetail(customerId, authorization, participantId, xV, xFapiAuthDate, xFapiCustomerIpAddress, xClientHeaders, xClientUserAgent, xIdempotencyKey, xFapiCustomerLastLoggedTime, xFapiInteractionId);

        // TODO: test validations
    }
}
